/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'ClientHome': RouteRecordInfo<'ClientHome', '/client', Record<never, never>, Record<never, never>>,
    'Collection': RouteRecordInfo<'Collection', '/client/collection', Record<never, never>, Record<never, never>>,
    'HowToPlay': RouteRecordInfo<'HowToPlay', '/how-to-play', Record<never, never>, Record<never, never>>,
    'Sandbox': RouteRecordInfo<'Sandbox', '/client/sandbox', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Register': RouteRecordInfo<'Register', '/register', Record<never, never>, Record<never, never>>,
    'TutorialList': RouteRecordInfo<'TutorialList', '/tutorial', Record<never, never>, Record<never, never>>,
    'TutorialMission': RouteRecordInfo<'TutorialMission', '/tutorial/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
