export type Config = {
  MAX_MAIN_DECK_SIZE: number;
  MAX_MAIN_DECK_CARD_COPIES: number;

  MAX_DESTINY_DECK_SIZE: number;
  MAX_DESTINY_DECK_CARD_COPIES: number;

  INITIAL_HAND_SIZE: number;

  MAX_HAND_SIZE: number;
  CARDS_DRAWN_PER_TURN: number;

  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: number;
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: number;

  SHUFFLE_DECK_ON_GAME_START: boolean;

  BATTLEFIELD_SLOTS: number;
  BASE_SLOTS: number;

  MAX_MANA: number;
  MANA_REGEN_PER_TURN: number;

  PLAYER_MAX_LEVEL: number;
  MAX_HELD_EXP: number;
  EXP_GAIN_PER_TURN: number;
};

export const defaultConfig: Config = {
  MAX_MAIN_DECK_SIZE: 40,
  MAX_MAIN_DECK_CARD_COPIES: 3,

  MAX_DESTINY_DECK_SIZE: 10,
  MAX_DESTINY_DECK_CARD_COPIES: 1,

  INITIAL_HAND_SIZE: 4,
  MAX_HAND_SIZE: 8,
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 2,
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: 0,
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: 0,

  BATTLEFIELD_SLOTS: 5,
  BASE_SLOTS: 5,

  MAX_MANA: 8,

  MANA_REGEN_PER_TURN: 5,

  PLAYER_MAX_LEVEL: 5,
  MAX_HELD_EXP: 5,
  EXP_GAIN_PER_TURN: 1
};
