export type Config = {
  MAX_MAIN_DECK_SIZE: number;
  MAX_MAIN_DECK_CARD_COPIES: number;

  TALENT_COUNT: number;

  INITIAL_HAND_SIZE: number;
  MAX_HAND_SIZE: number;

  CARDS_DRAWN_PER_TURN: number;

  SHUFFLE_DECK_ON_GAME_START: boolean;

  MAX_RESOURCE_ACTIONS_PER_TURN: number;

  MAX_MANA: number;
  MANA_REGEN_PER_TURN: number;

  MAX_MULLIGANED_CARDS: number;
  MAX_MOVEMENT_PER_TURN: number;
  MAX_ATTACKS_PER_TURN: number;
  MAX_COUNTERATTACKS_PER_TURN: number;
  MAX_EQUIPPED_ARTIFACTS: number;
  DRAW_STEP: 'turn-start' | 'turn-end';

  PLAYER_MAX_LEVEL: number;
  MAX_HELD_EXP: number;
  EXP_GAIN_PER_TURN: number;
};

export const defaultConfig: Config = {
  MAX_MAIN_DECK_SIZE: 40,
  MAX_MAIN_DECK_CARD_COPIES: 3,
  TALENT_COUNT: 10,
  INITIAL_HAND_SIZE: 5,
  MAX_HAND_SIZE: 7,

  DRAW_STEP: 'turn-start',
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 1,

  MAX_MANA: 8,
  MANA_REGEN_PER_TURN: 5,

  MAX_MULLIGANED_CARDS: 0,
  MAX_MOVEMENT_PER_TURN: 1,

  MAX_ATTACKS_PER_TURN: 1,
  MAX_COUNTERATTACKS_PER_TURN: Infinity,

  MAX_EQUIPPED_ARTIFACTS: 2,
  MAX_RESOURCE_ACTIONS_PER_TURN: 1,

  PLAYER_MAX_LEVEL: 4,
  MAX_HELD_EXP: 5,
  EXP_GAIN_PER_TURN: 1
};
