export type Config = {
  MAX_MAIN_DECK_SIZE: number;
  MAX_MAIN_DECK_CARD_COPIES: number;

  MAX_DESTINY_DECK_SIZE: number;
  MAX_DESTINY_DECK_CARD_COPIES: number;

  INITIAL_HAND_SIZE: number;
  INITAL_CARDS_IN_DESTINY_ZONE: number;

  MAX_HAND_SIZE: number;
  CARDS_DRAWN_PER_TURN: number;

  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: number;
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: number;

  SHUFFLE_DECK_ON_GAME_START: boolean;

  ATTACK_ZONE_SLOTS: number;
  DEFENSE_ZONE_SLOTS: number;

  MAX_EQUIPPED_ARTIFACTS: number;

  SUMMONING_SICKNESS: boolean;

  MINIMUM_TURN_COUNT_TO_PLAY_DESTINY_CARD: number;

  DEFINITIVE_PASSES: boolean;

  ALLOW_MINION_MOVEMENT: boolean;

  REWARD_FOR_PASSING_FIRST: boolean;

  MAX_RESOURCE_ACTIONS_PER_TURN: number;

  BASE_LOYALTY_HP_COST: number;
  BASE_LOYALTY_COST_INCREASE: number;
  BASE_LOYALTY_RUNE_CONSUMPTION: number;
};

export const defaultConfig: Config = {
  MAX_MAIN_DECK_SIZE: 60,
  MAX_MAIN_DECK_CARD_COPIES: 4,

  MAX_DESTINY_DECK_SIZE: 12,
  MAX_DESTINY_DECK_CARD_COPIES: 1,

  INITIAL_HAND_SIZE: 0,
  INITAL_CARDS_IN_DESTINY_ZONE: 0,
  MAX_HAND_SIZE: 999,
  SHUFFLE_DECK_ON_GAME_START: true,
  CARDS_DRAWN_PER_TURN: 1,
  PLAYER_1_CARDS_DRAWN_ON_FIRST_TURN: 0,
  PLAYER_2_CARDS_DRAWN_ON_FIRST_TURN: 0,

  ATTACK_ZONE_SLOTS: 7,
  DEFENSE_ZONE_SLOTS: 7,

  MAX_EQUIPPED_ARTIFACTS: 3,

  SUMMONING_SICKNESS: false,

  MINIMUM_TURN_COUNT_TO_PLAY_DESTINY_CARD: 0,

  DEFINITIVE_PASSES: true,

  ALLOW_MINION_MOVEMENT: false,

  REWARD_FOR_PASSING_FIRST: false,

  MAX_RESOURCE_ACTIONS_PER_TURN: 2,

  BASE_LOYALTY_HP_COST: 0,
  BASE_LOYALTY_COST_INCREASE: 0,
  BASE_LOYALTY_RUNE_CONSUMPTION: 1
};
